audit_header: false
title: Oregon Real Estate Video Blog with Laura Gillott
description: >-
  Our mission at Gillot Home Team is to be your best resource for Oregon real
  estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The Gillot Home Team, your professional
  Oregon Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: true
custom_links_new_tab:
  - title: Home Valuation
    url: 'https://www.teamgillott.com/info/cma'
  - title: Home Search
    url: 'https://www.teamgillott.com/search'
  - title: Market Overview
    url: 'https://www.teamgillott.com/info/market-statistics'
client:
  name: Laura Gillott
  title:
  license_number:
  about_markdown: >
    Laura Gillott is a top Realtor in Oregon since 1992. She loves Linn County
    and her hometown of Lebanon. Laura is married to David Gillott (local school
    teacher and licensed Realtor), and they have 3 adult children that all live
    in Lebanon. Laura built a team so she could serve Linn and Benton County
    with agents that share her standards and customer care. Laura was Realtor of
    the Year in 2002 and Woman of the Year in 2012. She enjoys being involved in
    local events, real estate education, and staying on top of the ever-changing
    technology and marketing. Laura is known for her honesty, hard work, and
    always putting her clients first. Laura is the team’s Lebanon Listing
    Specialist. Put Laura’s experience to work for you.
  brand: Gillott Home Team
  brokerage: Keller Williams Mid-Willamette
  market: Oregon
  address: '266 E Grant St.<br>Lebanon, OR 97355'
  phone: 541-451-2211
  phone_type:
  phone2:
  phone2_type:
  email: Laura@LauraGillott.com
  url: 'http://TeamGillott.com'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: What’s Your Oregon Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: 'https://www.teamgillott.com/info/cma'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: Looking for a Oregon Home?
    CTA_text2: Search the entire MLS for your Oregon home.
    CTA_link_text2: Search the MLS
    CTA_url2: 'https://www.teamgillott.com/search'
third_sidebar_CTA:
  - CTA_image_path3: /img/cta-images/003.jpg
    CTA_title3: Market Overview
    CTA_text3: Up to date Residential Real Estate Statistics
    CTA_link_text3: Statistics
    CTA_url3: 'https://www.teamgillott.com/info/market-statistics'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/LauraGillottHomeTeam/'
  linkedin_url:
  youtube_url: 'https://www.youtube.com/channel/UCQxoXbe3rGQpJinZ6G88pWw?view_as=subscriber'
  twitter_url: 'https://twitter.com/GillottHomeTeam'
  instagram_url: 'https://www.instagram.com/lauragillotthometeam/'
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Oregon Real Estate Podcast with -- CLIENT NAME --
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Oregon
    Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Gillot Home Team - your professional
    Oregon Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Oregon, home
    selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Oregon Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b21f24'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'